# Generated by Django 5.0.4 on 2024-05-07 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userdata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': [('view_profile_info', 'Can view profile information')]},
        ),
    ]
