# Generated by Django 5.0.4 on 2024-05-08 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_savedgraph'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='date',
            field=models.DateField(default='2003-05-21'),
        ),
        migrations.AddField(
            model_name='userdata',
            name='input',
            field=models.TextField(default='error'),
        ),
        migrations.AddField(
            model_name='userdata',
            name='which',
            field=models.CharField(default='dunno', max_length=100),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='name',
            field=models.CharField(default='harshit', max_length=200),
        ),
    ]
